### ISSUE TITLE
Methodes kunnen niet aangeroepen worden als er een '/' achter staat

### ISSUE THREAD

**Issue by blockswallower** [blockswallower/mvc#1]
Methodes worden netjes aangeroepen. Alleen als er een '/' achter staat en de methode 
verwacht geen argument, krijgen we een fatal error terug. 
Deze slash moet op de een of andere manier ge 'escaped' worden als
er verder geen arguments meer achter staan.

How to reproduce:
1. Maak een methode aan in bijvoorbeeld de index controller
2. Plak de methode naam vervolgens achter de controller naam in de URL.
3. Zet achter de methode een '/'
4. Je zal een error krijgen zodra je naar deze url wilt gaan.

**Comment by ploegnl** [comment]
Fix!
